import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div className=''>
      <Head>
        <title>Prince Muel Porfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className=''></main>

      <footer className=''></footer>
    </div>
  );
};

export default Home;
