name: Update Portfolio Website
on:
  push:
    tags:
      - "**"
  workflow_dispatch:
jobs:
  update-site:
    name: Update Portfolio Website On Markdown Update
    runs-on: ubuntu-latest
    steps:
      - name: REST API with curl
        run: |
          curl -X GET ${{secrets.REVALIDATE_URL}}
