name: Update Portfolio Website
on:
  push:
    tags:
      - "**"
  workflow_dispatch:
jobs:
  update-site:
    name: Update Portfolio Website On Markdown Update
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          REVALIDATE_URL: ${{ secrets.REVALIDATE_URL }}
        run: |
          curl -X GET "$REVALIDATE_URL"
